cc_binary(
    name = "core_node",
    srcs = [
        "core_node.cc",
    ],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "@org_llvm_libcxx//:libcxx",
        "//proto:core_node_cc_grpc",
    ],
)
