cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    deps = ["//toolchain/bazel_demo:hello_lib"],
)

cc_library(
    name = "hello_lib",
    srcs = ["hello_lib.cc"],
    hdrs = ["hello_lib.h"],
)
